HTML/HTML Attributes/HTML Attribute.md

Menambahkan Materi HTML Attribute

add: HTML Attribute

---

HTML/HTMLFilePath/README.md
HTML/HTMLIFrame/README.md

menambahkan beberapa basic dari html

Html basic

---

HTML/HTML Headings/HTML Headings.md

Menambahkan Materi HTML Headings

add: HTML Headings

---

HTML/HTML Paragraphs/HTML Paragraphs.md

Menambahkan materi HTML Paragraphs

add: HTML Paragraphs

---

HTML/HTML Style/HTML Style.md

add: HTML Style

---

HTML/HTMLEditors/HTMLEditors.md

HTMLEditors.md

---

HTML/HTML Paragraphs/HTML Paragraph-2.md

add: HTML Paragraph.md

---

HTML/HTML Images/HTML Images.md

Selamat pagi temen-temen, saya Ivan Andika Surya ingin menambahkan materi mengenai HTML Images yang belum ada pada repositori HTML-CSS. Materi ini menjelaskan dasar-dasar HTML Images dan **belum membahas mengenai styling** pada `<img>`. Semoga dapat dimerge dan berguna bagi temen-temen. Terimakasih!

add: Menambahkan materi tentang HTML Images

---

HTML/HTMLAttributes/HTMLAttributes.md

Menambahkan Atribut class dan id

add: Attributes class dan id

---

HTML/HTML Tables/HTML Tables.md
HTML/HTMLAttributes/HTMLAttributes.md

Menambahkan materi HTML Tables

add: HTML Tables

---

CSS/CSS Flexbox/CSS Flexbox.md

Menambahkan materi tentang CSS Flexbox

CSS Flexbox

---

CSS/CSS Comments/CSS Comments.md

saya menambahkan bagian css comments pada dokumentasi css

add: menambahkan dokumentasi css comments

---

HTML/HTML Semantic/HTML Semantic.md

Updatenya HTML Semantic.md

---

CSS/CSS Variable/CSS Variable.md

Saya membuat sebuah pull request untuk menjelaskan tentang CSS Variable

Membuat folder CSS Variable

---

HTML/HTMLCSS/HTML CSS.md

add: HTML CSS

---

HTML/HTMLAttributes/HTMLAttributes.md

docs: menambahkan atribut method

---

Template/readme.md

add: menambahkan link website template

---

.mergify.yml

menambahkan automatic bot untuk menambahkan label setiap file yang dirubah dan request review tim yang berhubungan dengan file tersebut.
jangan lupa dari tim untuk menambahkan label ``ready-to-merge`` untuk, otomatis squash
tidak menggunakan testing untuk yaml

feat: menambahkan automation bot

---

.mergify.yml

update bot mencakup:
- mengucapkan terima kasih ketika label ``ready-to-merge``
- menambahkan label ``sudah direview !``
tidak menggunakan testing untuk file yaml

feat: update bot

---

CSS/000 CSS Introduction/README.md

Saya menambah materi CSS baru yaitu `001 CSS Introduction`.
**Source**
- [W3School](https://www.w3schools.com/css/css_intro.asp)
- [MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps)
Saya menggunakan :
- ``os`` = `` windows``

add: materi CSS Introduction

---

CSS/023 CSS Display/README.md

Menambahkan materi CSS baru yaitu display. Materi ini menjelaskan beberapa penggunaan _value_ dari properti display di CSS, yaitu `inline`, `block`, `inline-block`, `table`, dan `flow-root` dan merujuk display `flex` dan `grid` pada materinya tersendiri.

add: Materi CSS ke 023 tentang Display

---

CSS/002 CSS Basic/README.md

fix: memperbaiki kode pada inline dan internal css

---

CSS/019 CSS Web Font/README.md

Memberikan `font-family` pada `@font-face`, dan cara menggunakannya. Supaya dapat mengetahui bagaimana cara menggunakan dan mencobanya. Sehingga dapat menghindari pembaca bingung
"loh, gimana cara gunainnya ini? Nama font di CSS-nya apa?"
Serta memberikan sumber tambahan dari [stackoverflow](https://stackoverflow.com/questions/12812441/how-do-i-use-woff-fonts-for-my-website).
linked issue #234

feat: Memberikan `font-family` pada `@font-face`

---

CSS/032 CSS Attribute Selectors/README.md

Saya telah membuat materi baru tentang CSS Attribute Selectors, dengan bersumber dari :
- [W3 Schools](https://www.w3schools.com/css/css_attribute_selectors.asp)
- [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors)
linked issue #204

add: Menambahkan Materi CSS Baru 032 CSS Attribute Selectors

---

HTML/002 HTML Basic/README.md

fix: kesalahan penulisan tag

---

HTML/027 HTML Meta/README.md

feat: add opengraph into META section

---

HTML/014 HTML HyperLink/README.md

docs: merapihkan dokumentasi html hyperlink

---

CSS/020 CSS Google Fonts/README.MD

docs: menambahkan materi css google fonts

---

HTML/004 HTML Elements/README.md

add: nesting elemen HTML

---

HTML/038 HTML Select/README.md

- ``os`` = ``linux / windows / macOS``

docs: menambah materi HTML Select

---

HTML/028 HTML Base/README.md

Menambahkan materi HTML Base
linked issue #203

docs: 028 HTML Base

---

HTML/033 HTML Symbols/README.md

Saya menambahkan materi 033 HTML Symbols, materi yang saya ajukan ini merupakan perbaikan dari PR #228 yang belum di merge.
- ``os`` = ``linux / windows / macOS``
linked issue #203

docs: 033 HTML Symbols

---

HTML/051 HTML Section/README.md

add: menambahkan materi tentang HTML Section Element

---

HTML/045 HTML Multimedia/README.md

add: 045 HTML Multimedia

---

HTML/039 HTML Input Attributes/README.md

Halo semuanya, disini saya menambahkan materi baru tentang HTML Input Attributes.
linked issue #203 203

docs: menambahkan materi 039 HTML Input Attributes

---

CSS/033 CSS Counters/README.md

Halo semuanya, disini saya menambahkan materi baru tentang CSS Counters.
linked issue #204

docs: menambahkan materi 033 CSS Counters
